// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

export namespace Routes {
    export const path = "sports.yahoo.com";

    export const Odds = { path: "sports.yahoo.com/odds" };
    export const Soccer = { path: "sports.yahoo.com/soccer" };
    export const Golf = { path: "sports.yahoo.com/golf" };
    export namespace Nba {
        export const path = "sports.yahoo.com/nba";

        export const News = { path: "sports.yahoo.com/nba/news" };
        export const Scoreboard = { path: "sports.yahoo.com/nba/scoreboard" };
        export const Stats = { path: "sports.yahoo.com/nba/stats" };
        export const Teams = { path: "sports.yahoo.com/nba/teams" };
        export const Players = { path: "sports.yahoo.com/nba/players" };
        export const Injuries = { path: "sports.yahoo.com/nba/injuries" };
        
    }

    export namespace Sportsbook {
        export const path = "sports.yahoo.com/sportsbook";

        export const News = { path: "sports.yahoo.com/sportsbook/news" };
        export const Experts = { path: "sports.yahoo.com/sportsbook/experts" };
        
    }
}