import fs from 'fs';
import { BaseRoute } from './base-route';
import { Utils } from './utils';

export function generate(inputFile: string, outputFile: string) {
    // get json file from command line
    const jsonFileInput = process.argv[2];
    if (!fs.existsSync(jsonFileInput)) {
        console.error(`File ${jsonFileInput} does not exist`);
        process.exit(1);
    }
    
    // read json file
    const routesJson = JSON.parse(fs.readFileSync(jsonFileInput, 'utf8'));
    if (!routesJson.domain) {
        console.error('Domain is required');
        process.exit(1);
    }
    
    // create root object
    const root = new BaseRoute('Routes', routesJson.domain, 0);
    
    // create all routes recursively under the root object
    Utils.buildRoutes(root, routesJson.routes);
    
    // stringify the root object to namespace
    let routesNs: string = root.stringifyToNamespace();
    
    // add warning to top of file to not edit directly
    routesNs = `// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n\n${routesNs}`;
    
    // use in default location if outfile not provided
    const outfile = !!routesJson.outfile ? routesJson.outfile : './dist/routes.ns.ts';
    Utils.createFile(outfile, routesNs);
}